## Markov Decision Processes

In [1]:
import numpy as np
import pandas as pd

from environment import GridWorld5x5, GridWorld10x10, GridWorld3x4
from mdpagent import MDPAgent

### Grid world

In [2]:
actions = ['left', 'up', 'right', 'down']

model = GridWorld5x5(actions)
# model = GridWorld10x10(actions)
# model = GridWorld3x4(actions)

mdpAgent = MDPAgent(model.n_states, model.n_actions, model.action_sets, discount=0.9, 
                    threshold=0.0001, max_iter=1000, verbose=True)

In [3]:
pi = np.ones((model.n_states, model.n_actions)) / model.n_actions
mdpAgent.iterative_policy_evaluation(model, pi)

Iterative Policy Evaluation: iteration 1, delta 19.500000
Iterative Policy Evaluation: iteration 2, delta 12.600000
Iterative Policy Evaluation: iteration 3, delta 7.644375
Iterative Policy Evaluation: iteration 4, delta 5.245383
Iterative Policy Evaluation: iteration 5, delta 3.507316
Iterative Policy Evaluation: iteration 6, delta 2.533802
Iterative Policy Evaluation: iteration 7, delta 1.757414
Iterative Policy Evaluation: iteration 8, delta 1.233562
Iterative Policy Evaluation: iteration 9, delta 0.875924
Iterative Policy Evaluation: iteration 10, delta 0.597858
Iterative Policy Evaluation: iteration 11, delta 0.429113
Iterative Policy Evaluation: iteration 12, delta 0.292723
Iterative Policy Evaluation: iteration 13, delta 0.211146
Iterative Policy Evaluation: iteration 14, delta 0.152113
Iterative Policy Evaluation: iteration 15, delta 0.111109
Iterative Policy Evaluation: iteration 16, delta 0.083551
Iterative Policy Evaluation: iteration 17, delta 0.065910
Iterative Policy Evaluation: iteration 18, delta 0.053138
Iterative Policy Evaluation: iteration 19, delta 0.043704
Iterative Policy Evaluation: iteration 20, delta 0.036940
Iterative Policy Evaluation: iteration 21, delta 0.032685
Iterative Policy Evaluation: iteration 22, delta 0.028458
Iterative Policy Evaluation: iteration 23, delta 0.025667
Iterative Policy Evaluation: iteration 24, delta 0.023074
Iterative Policy Evaluation: iteration 25, delta 0.021167
Iterative Policy Evaluation: iteration 26, delta 0.019195
Iterative Policy Evaluation: iteration 27, delta 0.017479
Iterative Policy Evaluation: iteration 28, delta 0.015814
Iterative Policy Evaluation: iteration 29, delta 0.014336
Iterative Policy Evaluation: iteration 30, delta 0.012949
Iterative Policy Evaluation: iteration 31, delta 0.011708
Iterative Policy Evaluation: iteration 32, delta 0.010563
Iterative Policy Evaluation: iteration 33, delta 0.009534
Iterative Policy Evaluation: iteration 34, delta 0.008595
Iterative Policy Evaluation: iteration 35, delta 0.007750
Iterative Policy Evaluation: iteration 36, delta 0.006982
Iterative Policy Evaluation: iteration 37, delta 0.006292
Iterative Policy Evaluation: iteration 38, delta 0.005667
Iterative Policy Evaluation: iteration 39, delta 0.005104
Iterative Policy Evaluation: iteration 40, delta 0.004596
Iterative Policy Evaluation: iteration 41, delta 0.004138
Iterative Policy Evaluation: iteration 42, delta 0.003726
Iterative Policy Evaluation: iteration 43, delta 0.003354
Iterative Policy Evaluation: iteration 44, delta 0.003019
Iterative Policy Evaluation: iteration 45, delta 0.002718
Iterative Policy Evaluation: iteration 46, delta 0.002447
Iterative Policy Evaluation: iteration 47, delta 0.002202
Iterative Policy Evaluation: iteration 48, delta 0.001982
Iterative Policy Evaluation: iteration 49, delta 0.001784
Iterative Policy Evaluation: iteration 50, delta 0.001606
Iterative Policy Evaluation: iteration 51, delta 0.001445
Iterative Policy Evaluation: iteration 52, delta 0.001301
Iterative Policy Evaluation: iteration 53, delta 0.001171
Iterative Policy Evaluation: iteration 54, delta 0.001054
Iterative Policy Evaluation: iteration 55, delta 0.000948
Iterative Policy Evaluation: iteration 56, delta 0.000854
Iterative Policy Evaluation: iteration 57, delta 0.000768
Iterative Policy Evaluation: iteration 58, delta 0.000691
Iterative Policy Evaluation: iteration 59, delta 0.000622
Iterative Policy Evaluation: iteration 60, delta 0.000560
Iterative Policy Evaluation: iteration 61, delta 0.000504
Iterative Policy Evaluation: iteration 62, delta 0.000454
Iterative Policy Evaluation: iteration 63, delta 0.000408
Iterative Policy Evaluation: iteration 64, delta 0.000367
Iterative Policy Evaluation: iteration 65, delta 0.000331
Iterative Policy Evaluation: iteration 66, delta 0.000298
Iterative Policy Evaluation: iteration 67, delta 0.000268
Iterative Policy Evaluation: iteration 68, delta 0.000241
Iterative Policy Evaluation: iteration 69, delta 0.000217
Iterative Policy Evaluation: iteration 70, delta 0.000195
Iterative Policy Evaluation: iteration 71, delta 0.000176
Iterative Policy Evaluation: iteration 72, delta 0.000158
Iterative Policy Evaluation: iteration 73, delta 0.000142
Iterative Policy Evaluation: iteration 74, delta 0.000128
Iterative Policy Evaluation: iteration 75, delta 0.000115
Iterative Policy Evaluation: iteration 76, delta 0.000104
Iterative Policy Evaluation: iteration 77, delta 0.000093

In [4]:
df = model.show_state_value(mdpAgent.U)
df

          0         1         2         3         4
0  3.309030  8.789326  4.427653  5.322401  1.492212
1  1.521622  2.992351  2.250174  1.907605  0.547436
2  0.050856  0.738204  0.673147  0.358220 -0.403108
3 -0.973559 -0.435462 -0.354849 -0.585571 -1.183041
4 -1.857667 -1.345198 -1.229234 -1.422885 -1.975145

### Policy iteration

In [5]:
mdpAgent.reset()
mdpAgent.policy_iteration(model)

Iterative Policy Evaluation: iteration 1, delta 21.000000
Iterative Policy Evaluation: iteration 2, delta 11.700000
Iterative Policy Evaluation: iteration 3, delta 7.290000
Iterative Policy Evaluation: iteration 4, delta 6.561000
Iterative Policy Evaluation: iteration 5, delta 5.904900
Iterative Policy Evaluation: iteration 6, delta 5.314410
Iterative Policy Evaluation: iteration 7, delta 4.782969
Iterative Policy Evaluation: iteration 8, delta 4.304672
Iterative Policy Evaluation: iteration 9, delta 3.874205
Iterative Policy Evaluation: iteration 10, delta 3.486784
Iterative Policy Evaluation: iteration 11, delta 3.138106
Iterative Policy Evaluation: iteration 12, delta 2.824295
Iterative Policy Evaluation: iteration 13, delta 2.541866
Iterative Policy Evaluation: iteration 14, delta 2.287679
Iterative Policy Evaluation: iteration 15, delta 2.058911
Iterative Policy Evaluation: iteration 16, delta 1.853020
Iterative Policy Evaluation: iteration 17, delta 1.667718
Iterative Policy Evaluation: iteration 18, delta 1.500946
Iterative Policy Evaluation: iteration 19, delta 1.350852
Iterative Policy Evaluation: iteration 20, delta 1.215767
Iterative Policy Evaluation: iteration 21, delta 1.094190
Iterative Policy Evaluation: iteration 22, delta 0.984771
Iterative Policy Evaluation: iteration 23, delta 0.886294
Iterative Policy Evaluation: iteration 24, delta 0.797664
Iterative Policy Evaluation: iteration 25, delta 0.717898
Iterative Policy Evaluation: iteration 26, delta 0.646108
Iterative Policy Evaluation: iteration 27, delta 0.581497
Iterative Policy Evaluation: iteration 28, delta 0.523348
Iterative Policy Evaluation: iteration 29, delta 0.471013
Iterative Policy Evaluation: iteration 30, delta 0.423912
Iterative Policy Evaluation: iteration 31, delta 0.381520
Iterative Policy Evaluation: iteration 32, delta 0.343368
Iterative Policy Evaluation: iteration 33, delta 0.309032
Iterative Policy Evaluation: iteration 34, delta 0.278128
Iterative Policy Evaluation: iteration 35, delta 0.250316
Iterative Policy Evaluation: iteration 36, delta 0.225284
Iterative Policy Evaluation: iteration 37, delta 0.202756
Iterative Policy Evaluation: iteration 38, delta 0.182480
Iterative Policy Evaluation: iteration 39, delta 0.164232
Iterative Policy Evaluation: iteration 40, delta 0.147809
Iterative Policy Evaluation: iteration 41, delta 0.133028
Iterative Policy Evaluation: iteration 42, delta 0.119725
Iterative Policy Evaluation: iteration 43, delta 0.107753
Iterative Policy Evaluation: iteration 44, delta 0.096977
Iterative Policy Evaluation: iteration 45, delta 0.087280
Iterative Policy Evaluation: iteration 46, delta 0.078552
Iterative Policy Evaluation: iteration 47, delta 0.070697
Iterative Policy Evaluation: iteration 48, delta 0.063627
Iterative Policy Evaluation: iteration 49, delta 0.057264
Iterative Policy Evaluation: iteration 50, delta 0.051538
Iterative Policy Evaluation: iteration 51, delta 0.046384
Iterative Policy Evaluation: iteration 52, delta 0.041746
Iterative Policy Evaluation: iteration 53, delta 0.037571
Iterative Policy Evaluation: iteration 54, delta 0.033814
Iterative Policy Evaluation: iteration 55, delta 0.030433
Iterative Policy Evaluation: iteration 56, delta 0.027389
Iterative Policy Evaluation: iteration 57, delta 0.024650
Iterative Policy Evaluation: iteration 58, delta 0.022185
Iterative Policy Evaluation: iteration 59, delta 0.019967
Iterative Policy Evaluation: iteration 60, delta 0.017970
Iterative Policy Evaluation: iteration 61, delta 0.016173
Iterative Policy Evaluation: iteration 62, delta 0.014556
Iterative Policy Evaluation: iteration 63, delta 0.013100
Iterative Policy Evaluation: iteration 64, delta 0.011790
Iterative Policy Evaluation: iteration 65, delta 0.010611
Iterative Policy Evaluation: iteration 66, delta 0.009550
Iterative Policy Evaluation: iteration 67, delta 0.008595
Iterative Policy Evaluation: iteration 68, delta 0.007736
Iterative Policy Evaluation: iteration 69, delta 0.006962
Iterative Policy Evaluation: iteration 70, delta 0.006266
Iterative Policy Evaluation: iteration 71, delta 0.005639
Iterative Policy Evaluation: iteration 72, delta 0.005075
Iterative Policy Evaluation: iteration 73, delta 0.004568
Iterative Policy Evaluation: iteration 74, delta 0.004111
Iterative Policy Evaluation: iteration 75, delta 0.003700
Iterative Policy Evaluation: iteration 76, delta 0.003330
Iterative Policy Evaluation: iteration 77, delta 0.002997
Iterative Policy Evaluation: iteration 78, delta 0.002697
Iterative Policy Evaluation: iteration 79, delta 0.002427
Iterative Policy Evaluation: iteration 80, delta 0.002185
Iterative Policy Evaluation: iteration 81, delta 0.001966
Iterative Policy Evaluation: iteration 82, delta 0.001770
Iterative Policy Evaluation: iteration 83, delta 0.001593
Iterative Policy Evaluation: iteration 84, delta 0.001433
Iterative Policy Evaluation: iteration 85, delta 0.001290
Iterative Policy Evaluation: iteration 86, delta 0.001161
Iterative Policy Evaluation: iteration 87, delta 0.001045
Iterative Policy Evaluation: iteration 88, delta 0.000940
Iterative Policy Evaluation: iteration 89, delta 0.000846
Iterative Policy Evaluation: iteration 90, delta 0.000762
Iterative Policy Evaluation: iteration 91, delta 0.000686
Iterative Policy Evaluation: iteration 92, delta 0.000617
Iterative Policy Evaluation: iteration 93, delta 0.000555
Iterative Policy Evaluation: iteration 94, delta 0.000500
Iterative Policy Evaluation: iteration 95, delta 0.000450
Iterative Policy Evaluation: iteration 96, delta 0.000405
Iterative Policy Evaluation: iteration 97, delta 0.000364
Iterative Policy Evaluation: iteration 98, delta 0.000328
Iterative Policy Evaluation: iteration 99, delta 0.000295
Iterative Policy Evaluation: iteration 100, delta 0.000266
Iterative Policy Evaluation: iteration 101, delta 0.000239
Iterative Policy Evaluation: iteration 102, delta 0.000215
Iterative Policy Evaluation: iteration 103, delta 0.000194
Iterative Policy Evaluation: iteration 104, delta 0.000174
Iterative Policy Evaluation: iteration 105, delta 0.000157
Iterative Policy Evaluation: iteration 106, delta 0.000141
Iterative Policy Evaluation: iteration 107, delta 0.000127
Iterative Policy Evaluation: iteration 108, delta 0.000114
Iterative Policy Evaluation: iteration 109, delta 0.000103
Iterative Policy Evaluation: iteration 110, delta 0.000093
Policy Iteration: iteration 1, delta 34.000000
Iterative Policy Evaluation: iteration 1, delta 86.369518
Iterative Policy Evaluation: iteration 2, delta 20.817075
Iterative Policy Evaluation: iteration 3, delta 18.735375
Iterative Policy Evaluation: iteration 4, delta 24.669421
Iterative Policy Evaluation: iteration 5, delta 24.446456
Iterative Policy Evaluation: iteration 6, delta 28.325964
Iterative Policy Evaluation: iteration 7, delta 33.241595
Iterative Policy Evaluation: iteration 8, delta 32.586199
Iterative Policy Evaluation: iteration 9, delta 22.315376
Iterative Policy Evaluation: iteration 10, delta 14.435388
Iterative Policy Evaluation: iteration 11, delta 16.726198
Iterative Policy Evaluation: iteration 12, delta 19.628830
Iterative Policy Evaluation: iteration 13, delta 19.241825
Iterative Policy Evaluation: iteration 14, delta 13.177007
Iterative Policy Evaluation: iteration 15, delta 8.523952
Iterative Policy Evaluation: iteration 16, delta 9.876653
Iterative Policy Evaluation: iteration 17, delta 11.590628
Iterative Policy Evaluation: iteration 18, delta 11.362105
Iterative Policy Evaluation: iteration 19, delta 7.780891
Iterative Policy Evaluation: iteration 20, delta 5.033309
Iterative Policy Evaluation: iteration 21, delta 5.832065
Iterative Policy Evaluation: iteration 22, delta 6.844150
Iterative Policy Evaluation: iteration 23, delta 6.709209
Iterative Policy Evaluation: iteration 24, delta 4.594538
Iterative Policy Evaluation: iteration 25, delta 2.972118
Iterative Policy Evaluation: iteration 26, delta 3.443776
Iterative Policy Evaluation: iteration 27, delta 4.041402
Iterative Policy Evaluation: iteration 28, delta 3.961721
Iterative Policy Evaluation: iteration 29, delta 2.713029
Iterative Policy Evaluation: iteration 30, delta 1.755006
Iterative Policy Evaluation: iteration 31, delta 2.033515
Iterative Policy Evaluation: iteration 32, delta 2.386407
Iterative Policy Evaluation: iteration 33, delta 2.339357
Iterative Policy Evaluation: iteration 34, delta 1.602016
Iterative Policy Evaluation: iteration 35, delta 1.036314
Iterative Policy Evaluation: iteration 36, delta 1.200770
Iterative Policy Evaluation: iteration 37, delta 1.409150
Iterative Policy Evaluation: iteration 38, delta 1.381367
Iterative Policy Evaluation: iteration 39, delta 0.945975
Iterative Policy Evaluation: iteration 40, delta 0.611933
Iterative Policy Evaluation: iteration 41, delta 0.709043
Iterative Policy Evaluation: iteration 42, delta 0.832089
Iterative Policy Evaluation: iteration 43, delta 0.815683
Iterative Policy Evaluation: iteration 44, delta 0.558589
Iterative Policy Evaluation: iteration 45, delta 0.361340
Iterative Policy Evaluation: iteration 46, delta 0.418683
Iterative Policy Evaluation: iteration 47, delta 0.491340
Iterative Policy Evaluation: iteration 48, delta 0.481653
Iterative Policy Evaluation: iteration 49, delta 0.329841
Iterative Policy Evaluation: iteration 50, delta 0.213368
Iterative Policy Evaluation: iteration 51, delta 0.247228
Iterative Policy Evaluation: iteration 52, delta 0.290131
Iterative Policy Evaluation: iteration 53, delta 0.284411
Iterative Policy Evaluation: iteration 54, delta 0.194768
Iterative Policy Evaluation: iteration 55, delta 0.125992
Iterative Policy Evaluation: iteration 56, delta 0.145986
Iterative Policy Evaluation: iteration 57, delta 0.171320
Iterative Policy Evaluation: iteration 58, delta 0.167942
Iterative Policy Evaluation: iteration 59, delta 0.115008
Iterative Policy Evaluation: iteration 60, delta 0.074397
Iterative Policy Evaluation: iteration 61, delta 0.086203
Iterative Policy Evaluation: iteration 62, delta 0.101163
Iterative Policy Evaluation: iteration 63, delta 0.099168
Iterative Policy Evaluation: iteration 64, delta 0.067911
Iterative Policy Evaluation: iteration 65, delta 0.043931
Iterative Policy Evaluation: iteration 66, delta 0.050902
Iterative Policy Evaluation: iteration 67, delta 0.059735
Iterative Policy Evaluation: iteration 68, delta 0.058558
Iterative Policy Evaluation: iteration 69, delta 0.040101
Iterative Policy Evaluation: iteration 70, delta 0.025941
Iterative Policy Evaluation: iteration 71, delta 0.030057
Iterative Policy Evaluation: iteration 72, delta 0.035273
Iterative Policy Evaluation: iteration 73, delta 0.034578
Iterative Policy Evaluation: iteration 74, delta 0.023679
Iterative Policy Evaluation: iteration 75, delta 0.015318
Iterative Policy Evaluation: iteration 76, delta 0.017748
Iterative Policy Evaluation: iteration 77, delta 0.020828
Iterative Policy Evaluation: iteration 78, delta 0.020418
Iterative Policy Evaluation: iteration 79, delta 0.013982
Iterative Policy Evaluation: iteration 80, delta 0.009045
Iterative Policy Evaluation: iteration 81, delta 0.010480
Iterative Policy Evaluation: iteration 82, delta 0.012299
Iterative Policy Evaluation: iteration 83, delta 0.012057
Iterative Policy Evaluation: iteration 84, delta 0.008256
Iterative Policy Evaluation: iteration 85, delta 0.005341
Iterative Policy Evaluation: iteration 86, delta 0.006189
Iterative Policy Evaluation: iteration 87, delta 0.007262
Iterative Policy Evaluation: iteration 88, delta 0.007119
Iterative Policy Evaluation: iteration 89, delta 0.004875
Iterative Policy Evaluation: iteration 90, delta 0.003154
Iterative Policy Evaluation: iteration 91, delta 0.003654
Iterative Policy Evaluation: iteration 92, delta 0.004288
Iterative Policy Evaluation: iteration 93, delta 0.004204
Iterative Policy Evaluation: iteration 94, delta 0.002879
Iterative Policy Evaluation: iteration 95, delta 0.001862
Iterative Policy Evaluation: iteration 96, delta 0.002158
Iterative Policy Evaluation: iteration 97, delta 0.002532
Iterative Policy Evaluation: iteration 98, delta 0.002482
Iterative Policy Evaluation: iteration 99, delta 0.001700
Iterative Policy Evaluation: iteration 100, delta 0.001100
Iterative Policy Evaluation: iteration 101, delta 0.001274
Iterative Policy Evaluation: iteration 102, delta 0.001495
Iterative Policy Evaluation: iteration 103, delta 0.001466
Iterative Policy Evaluation: iteration 104, delta 0.001004
Iterative Policy Evaluation: iteration 105, delta 0.000649
Iterative Policy Evaluation: iteration 106, delta 0.000752
Iterative Policy Evaluation: iteration 107, delta 0.000883
Iterative Policy Evaluation: iteration 108, delta 0.000866
Iterative Policy Evaluation: iteration 109, delta 0.000593
Iterative Policy Evaluation: iteration 110, delta 0.000383
Iterative Policy Evaluation: iteration 111, delta 0.000444
Iterative Policy Evaluation: iteration 112, delta 0.000521
Iterative Policy Evaluation: iteration 113, delta 0.000511
Iterative Policy Evaluation: iteration 114, delta 0.000350
Iterative Policy Evaluation: iteration 115, delta 0.000226
Iterative Policy Evaluation: iteration 116, delta 0.000262
Iterative Policy Evaluation: iteration 117, delta 0.000308
Iterative Policy Evaluation: iteration 118, delta 0.000302
Iterative Policy Evaluation: iteration 119, delta 0.000207
Iterative Policy Evaluation: iteration 120, delta 0.000134
Iterative Policy Evaluation: iteration 121, delta 0.000155
Iterative Policy Evaluation: iteration 122, delta 0.000182
Iterative Policy Evaluation: iteration 123, delta 0.000178
Iterative Policy Evaluation: iteration 124, delta 0.000122
Iterative Policy Evaluation: iteration 125, delta 0.000079
Policy Iteration: iteration 2, delta 9.000000
Iterative Policy Evaluation: iteration 1, delta 4.824374
Iterative Policy Evaluation: iteration 2, delta 0.291962
Iterative Policy Evaluation: iteration 3, delta 0.000094
Policy Iteration: iteration 3, delta 0.000000

In [6]:
df = model.show_state_value(mdpAgent.U)
df

           0          1          2          3          4
0  21.977461  24.419401  21.977461  19.419401  17.477461
1  19.779702  21.977461  19.779702  17.801732  16.021556
2  17.801732  19.779702  17.801732  16.021556  14.419401
3  16.021556  17.801732  16.021556  14.419401  12.977461
4  14.419401  16.021556  14.419401  12.977461  11.679702

In [7]:
mdpAgent.extract_policy()
df = model.show_policy(mdpAgent.pi)
df

       0     1     2     3     4
0  right  left  left  left  left
1     up    up  left  left  left
2     up    up  left  left  left
3     up    up  left  left  left
4     up    up  left  left  left

In [8]:
df = model.show_action_value(mdpAgent.Q)
df

,0,1,2,3,4
0,"{'left': 18.78, 'up': 18.78, 'right': 21.98, '...","{'left': 24.42, 'up': 24.42, 'right': 24.42, '...","{'left': 21.98, 'up': 18.78, 'right': 17.48, '...","{'left': 19.42, 'up': 19.42, 'right': 19.42, '...","{'left': 17.48, 'up': 14.73, 'right': 14.73, '..."
1,"{'left': 16.8, 'up': 19.78, 'right': 19.78, 'd...","{'left': 17.8, 'up': 21.98, 'right': 17.8, 'do...","{'left': 19.78, 'up': 19.78, 'right': 16.02, '...","{'left': 17.8, 'up': 17.48, 'right': 14.42, 'd...","{'left': 16.02, 'up': 15.73, 'right': 13.42, '..."
2,"{'left': 15.02, 'up': 17.8, 'right': 17.8, 'do...","{'left': 16.02, 'up': 19.78, 'right': 16.02, '...","{'left': 17.8, 'up': 17.8, 'right': 14.42, 'do...","{'left': 16.02, 'up': 16.02, 'right': 12.98, '...","{'left': 14.42, 'up': 14.42, 'right': 11.98, '..."
3,"{'left': 13.42, 'up': 16.02, 'right': 16.02, '...","{'left': 14.42, 'up': 17.8, 'right': 14.42, 'd...","{'left': 16.02, 'up': 16.02, 'right': 12.98, '...","{'left': 14.42, 'up': 14.42, 'right': 11.68, '...","{'left': 12.98, 'up': 12.98, 'right': 10.68, '..."
4,"{'left': 11.98, 'up': 14.42, 'right': 14.42, '...","{'left': 12.98, 'up': 16.02, 'right': 12.98, '...","{'left': 14.42, 'up': 14.42, 'right': 11.68, '...","{'left': 12.98, 'up': 12.98, 'right': 10.51, '...","{'left': 11.68, 'up': 11.68, 'right': 9.51, 'd..."

### Value iteration

In [9]:
mdpAgent.reset()
mdpAgent.value_iteration(model)

Value Iteration: iteration 1, delta 15.000000
Value Iteration: iteration 2, delta 36.000000
Value Iteration: iteration 3, delta 32.400000
Value Iteration: iteration 4, delta 35.595000
Value Iteration: iteration 5, delta 35.037000
Value Iteration: iteration 6, delta 28.329750
Value Iteration: iteration 7, delta 25.270785
Value Iteration: iteration 8, delta 21.270762
Value Iteration: iteration 9, delta 20.244556
Value Iteration: iteration 10, delta 19.560552
Value Iteration: iteration 11, delta 16.402679
Value Iteration: iteration 12, delta 14.412568
Value Iteration: iteration 13, delta 12.081650
Value Iteration: iteration 14, delta 11.974356
Value Iteration: iteration 15, delta 11.461099
Value Iteration: iteration 16, delta 9.723740
Value Iteration: iteration 17, delta 8.750517
Value Iteration: iteration 18, delta 6.955475
Value Iteration: iteration 19, delta 6.960453
Value Iteration: iteration 20, delta 7.013161
Value Iteration: iteration 21, delta 6.107863
Value Iteration: iteration 22, delta 5.364282
Value Iteration: iteration 23, delta 3.972189
Value Iteration: iteration 24, delta 3.920181
Value Iteration: iteration 25, delta 4.089810
Value Iteration: iteration 26, delta 3.842197
Value Iteration: iteration 27, delta 3.325183
Value Iteration: iteration 28, delta 2.193634
Value Iteration: iteration 29, delta 2.124931
Value Iteration: iteration 30, delta 2.363600
Value Iteration: iteration 31, delta 2.504344
Value Iteration: iteration 32, delta 2.240886
Value Iteration: iteration 33, delta 1.359002
Value Iteration: iteration 34, delta 1.236126
Value Iteration: iteration 35, delta 1.390642
Value Iteration: iteration 36, delta 1.501893
Value Iteration: iteration 37, delta 1.351704
Value Iteration: iteration 38, delta 0.811022
Value Iteration: iteration 39, delta 0.729920
Value Iteration: iteration 40, delta 0.821160
Value Iteration: iteration 41, delta 0.886853
Value Iteration: iteration 42, delta 0.798168
Value Iteration: iteration 43, delta 0.478901
Value Iteration: iteration 44, delta 0.431011
Value Iteration: iteration 45, delta 0.484887
Value Iteration: iteration 46, delta 0.523678
Value Iteration: iteration 47, delta 0.471310
Value Iteration: iteration 48, delta 0.282786
Value Iteration: iteration 49, delta 0.254507
Value Iteration: iteration 50, delta 0.286321
Value Iteration: iteration 51, delta 0.309227
Value Iteration: iteration 52, delta 0.278304
Value Iteration: iteration 53, delta 0.166982
Value Iteration: iteration 54, delta 0.150284
Value Iteration: iteration 55, delta 0.169070
Value Iteration: iteration 56, delta 0.182595
Value Iteration: iteration 57, delta 0.164336
Value Iteration: iteration 58, delta 0.098601
Value Iteration: iteration 59, delta 0.088741
Value Iteration: iteration 60, delta 0.099834
Value Iteration: iteration 61, delta 0.107821
Value Iteration: iteration 62, delta 0.097039
Value Iteration: iteration 63, delta 0.058223
Value Iteration: iteration 64, delta 0.052401
Value Iteration: iteration 65, delta 0.058951
Value Iteration: iteration 66, delta 0.063667
Value Iteration: iteration 67, delta 0.057300
Value Iteration: iteration 68, delta 0.034380
Value Iteration: iteration 69, delta 0.030942
Value Iteration: iteration 70, delta 0.034810
Value Iteration: iteration 71, delta 0.037595
Value Iteration: iteration 72, delta 0.033835
Value Iteration: iteration 73, delta 0.020301
Value Iteration: iteration 74, delta 0.018271
Value Iteration: iteration 75, delta 0.020555
Value Iteration: iteration 76, delta 0.022199
Value Iteration: iteration 77, delta 0.019979
Value Iteration: iteration 78, delta 0.011988
Value Iteration: iteration 79, delta 0.010789
Value Iteration: iteration 80, delta 0.012137
Value Iteration: iteration 81, delta 0.013108
Value Iteration: iteration 82, delta 0.011798
Value Iteration: iteration 83, delta 0.007079
Value Iteration: iteration 84, delta 0.006371
Value Iteration: iteration 85, delta 0.007167
Value Iteration: iteration 86, delta 0.007740
Value Iteration: iteration 87, delta 0.006966
Value Iteration: iteration 88, delta 0.004180
Value Iteration: iteration 89, delta 0.003762
Value Iteration: iteration 90, delta 0.004232
Value Iteration: iteration 91, delta 0.004571
Value Iteration: iteration 92, delta 0.004114
Value Iteration: iteration 93, delta 0.002468
Value Iteration: iteration 94, delta 0.002221
Value Iteration: iteration 95, delta 0.002499
Value Iteration: iteration 96, delta 0.002699
Value Iteration: iteration 97, delta 0.002429
Value Iteration: iteration 98, delta 0.001457
Value Iteration: iteration 99, delta 0.001312
Value Iteration: iteration 100, delta 0.001476
Value Iteration: iteration 101, delta 0.001594
Value Iteration: iteration 102, delta 0.001434
Value Iteration: iteration 103, delta 0.000861
Value Iteration: iteration 104, delta 0.000775
Value Iteration: iteration 105, delta 0.000871
Value Iteration: iteration 106, delta 0.000941
Value Iteration: iteration 107, delta 0.000847
Value Iteration: iteration 108, delta 0.000508
Value Iteration: iteration 109, delta 0.000457
Value Iteration: iteration 110, delta 0.000515
Value Iteration: iteration 111, delta 0.000556
Value Iteration: iteration 112, delta 0.000500
Value Iteration: iteration 113, delta 0.000300
Value Iteration: iteration 114, delta 0.000270
Value Iteration: iteration 115, delta 0.000304
Value Iteration: iteration 116, delta 0.000328
Value Iteration: iteration 117, delta 0.000295
Value Iteration: iteration 118, delta 0.000177
Value Iteration: iteration 119, delta 0.000159
Value Iteration: iteration 120, delta 0.000179
Value Iteration: iteration 121, delta 0.000194
Value Iteration: iteration 122, delta 0.000174
Value Iteration: iteration 123, delta 0.000105
Value Iteration: iteration 124, delta 0.000094

In [10]:
df = model.show_state_value(mdpAgent.U)
df

           0          1          2          3          4
0  21.977443  24.419382  21.977443  19.419382  17.477443
1  19.779699  21.977443  19.779699  17.801729  16.021535
2  17.801729  19.779699  17.801729  16.021535  14.419382
3  16.021535  17.801729  16.021535  14.419382  12.977443
4  14.419382  16.021535  14.419382  12.977443  11.679699

In [11]:
mdpAgent.extract_policy()
df = model.show_policy(mdpAgent.pi)
df

       0     1     2     3     4
0  right  left  left  left  left
1     up    up  left  left  left
2     up    up  left  left  left
3     up    up  left  left  left
4     up    up  left  left  left

In [12]:
df = model.show_action_value(mdpAgent.Q)
df

,0,1,2,3,4
0,"{'left': 18.78, 'up': 18.78, 'right': 21.98, '...","{'left': 24.42, 'up': 24.42, 'right': 24.42, '...","{'left': 21.98, 'up': 18.78, 'right': 17.48, '...","{'left': 19.42, 'up': 19.42, 'right': 19.42, '...","{'left': 17.48, 'up': 14.73, 'right': 14.73, '..."
1,"{'left': 16.8, 'up': 19.78, 'right': 19.78, 'd...","{'left': 17.8, 'up': 21.98, 'right': 17.8, 'do...","{'left': 19.78, 'up': 19.78, 'right': 16.02, '...","{'left': 17.8, 'up': 17.48, 'right': 14.42, 'd...","{'left': 16.02, 'up': 15.73, 'right': 13.42, '..."
2,"{'left': 15.02, 'up': 17.8, 'right': 17.8, 'do...","{'left': 16.02, 'up': 19.78, 'right': 16.02, '...","{'left': 17.8, 'up': 17.8, 'right': 14.42, 'do...","{'left': 16.02, 'up': 16.02, 'right': 12.98, '...","{'left': 14.42, 'up': 14.42, 'right': 11.98, '..."
3,"{'left': 13.42, 'up': 16.02, 'right': 16.02, '...","{'left': 14.42, 'up': 17.8, 'right': 14.42, 'd...","{'left': 16.02, 'up': 16.02, 'right': 12.98, '...","{'left': 14.42, 'up': 14.42, 'right': 11.68, '...","{'left': 12.98, 'up': 12.98, 'right': 10.68, '..."
4,"{'left': 11.98, 'up': 14.42, 'right': 14.42, '...","{'left': 12.98, 'up': 16.02, 'right': 12.98, '...","{'left': 14.42, 'up': 14.42, 'right': 11.68, '...","{'left': 12.98, 'up': 12.98, 'right': 10.51, '...","{'left': 11.68, 'up': 11.68, 'right': 9.51, 'd..."

### Gauss-Seidel value iteration

In [13]:
mdpAgent.reset()
mdpAgent.value_iteration_gs(model)

Gauss-Siedel Value Iteration: iteration 1, delta 134.940489
Gauss-Siedel Value Iteration: iteration 2, delta 122.146564
Gauss-Siedel Value Iteration: iteration 3, delta 72.126325
Gauss-Siedel Value Iteration: iteration 4, delta 42.589874
Gauss-Siedel Value Iteration: iteration 5, delta 25.148894
Gauss-Siedel Value Iteration: iteration 6, delta 14.850171
Gauss-Siedel Value Iteration: iteration 7, delta 8.768877
Gauss-Siedel Value Iteration: iteration 8, delta 5.177934
Gauss-Siedel Value Iteration: iteration 9, delta 3.057518
Gauss-Siedel Value Iteration: iteration 10, delta 1.805434
Gauss-Siedel Value Iteration: iteration 11, delta 1.066091
Gauss-Siedel Value Iteration: iteration 12, delta 0.629516
Gauss-Siedel Value Iteration: iteration 13, delta 0.371723
Gauss-Siedel Value Iteration: iteration 14, delta 0.219499
Gauss-Siedel Value Iteration: iteration 15, delta 0.129612
Gauss-Siedel Value Iteration: iteration 16, delta 0.076534
Gauss-Siedel Value Iteration: iteration 17, delta 0.045193
Gauss-Siedel Value Iteration: iteration 18, delta 0.026686
Gauss-Siedel Value Iteration: iteration 19, delta 0.015758
Gauss-Siedel Value Iteration: iteration 20, delta 0.009305
Gauss-Siedel Value Iteration: iteration 21, delta 0.005494
Gauss-Siedel Value Iteration: iteration 22, delta 0.003244
Gauss-Siedel Value Iteration: iteration 23, delta 0.001916
Gauss-Siedel Value Iteration: iteration 24, delta 0.001131
Gauss-Siedel Value Iteration: iteration 25, delta 0.000668
Gauss-Siedel Value Iteration: iteration 26, delta 0.000394
Gauss-Siedel Value Iteration: iteration 27, delta 0.000233
Gauss-Siedel Value Iteration: iteration 28, delta 0.000138
Gauss-Siedel Value Iteration: iteration 29, delta 0.000081

In [14]:
df = model.show_state_value(mdpAgent.U)
df

           0          1          2          3          4
0  21.977477  24.419422  21.977480  19.419422  17.477480
1  19.779729  21.977480  19.779732  17.801759  16.021583
2  17.801756  19.779732  17.801759  16.021583  14.419425
3  16.021580  17.801759  16.021583  14.419425  12.977482
4  14.419422  16.021583  14.419425  12.977482  11.679734

In [15]:
mdpAgent.extract_policy()
df = model.show_policy(mdpAgent.pi)
df

       0     1     2     3     4
0  right  left  left  left  left
1     up    up  left  left  left
2     up    up  left  left  left
3     up    up  left  left  left
4     up    up  left  left  left

In [16]:
df = model.show_action_value(mdpAgent.Q)
df

,0,1,2,3,4
0,"{'left': 18.78, 'up': 18.78, 'right': 21.98, '...","{'left': 24.42, 'up': 24.42, 'right': 24.42, '...","{'left': 21.98, 'up': 18.78, 'right': 17.48, '...","{'left': 19.42, 'up': 19.42, 'right': 19.42, '...","{'left': 17.48, 'up': 14.73, 'right': 14.73, '..."
1,"{'left': 16.8, 'up': 19.78, 'right': 19.78, 'd...","{'left': 17.8, 'up': 21.98, 'right': 17.8, 'do...","{'left': 19.78, 'up': 19.78, 'right': 16.02, '...","{'left': 17.8, 'up': 17.48, 'right': 14.42, 'd...","{'left': 16.02, 'up': 15.73, 'right': 13.42, '..."
2,"{'left': 15.02, 'up': 17.8, 'right': 17.8, 'do...","{'left': 16.02, 'up': 19.78, 'right': 16.02, '...","{'left': 17.8, 'up': 17.8, 'right': 14.42, 'do...","{'left': 16.02, 'up': 16.02, 'right': 12.98, '...","{'left': 14.42, 'up': 14.42, 'right': 11.98, '..."
3,"{'left': 13.42, 'up': 16.02, 'right': 16.02, '...","{'left': 14.42, 'up': 17.8, 'right': 14.42, 'd...","{'left': 16.02, 'up': 16.02, 'right': 12.98, '...","{'left': 14.42, 'up': 14.42, 'right': 11.68, '...","{'left': 12.98, 'up': 12.98, 'right': 10.68, '..."
4,"{'left': 11.98, 'up': 14.42, 'right': 14.42, '...","{'left': 12.98, 'up': 16.02, 'right': 12.98, '...","{'left': 14.42, 'up': 14.42, 'right': 11.68, '...","{'left': 12.98, 'up': 12.98, 'right': 10.51, '...","{'left': 11.68, 'up': 11.68, 'right': 9.51, 'd..."